### ISSUE TITLE
Unable to move the cursor in the messaging input area

### ISSUE THREAD

**Issue by lenny-horstink** [crusttech/webapp-messaging#33] opened 2019-04-01 13:45 UTC
When I'm writing a long message I cannot left click somewhere in it to easily edit the content.  I can click on the right mouse button to move the cursor where I want to (and continue typing at that place after clicking the left mouse button, but this workaround is not really convenient.

Moving the cursor with the arrow keys also behaves strange, because I can only move in one single row of text, but I cannot move to other rows.

Steps to reproduce:
- Enter firefox
- Type something like this:

![image](https://user-images.githubusercontent.com/44468809/55332084-f2635580-5494-11e9-8080-ce3de518829f.png)

- Try to add content behind the second "test" (row two).

Browser: Firefox (in Chrome it works ok)

**Comment by Fajfa** [comment] 2019-07-10 12:15
Weird bug. Everything works fine when editing a message, the problem is only when writing a new message. I cant figure out the reason why the text-inputs are behaving differently. They are the same component, just used with different props in a different place. 
I have tried playing around with the component props, no luck.

**Comment by Fajfa** [comment] 2019-07-10 12:23
Adding this to ql-editor solves the issue: 
-moz-user-select: text;
-khtml-user-select: text;
-webkit-user-select: text;
-ms-user-select: text;
user-select: text;

**Comment by Fajfa** [comment] 2019-07-10 12:28
Fixed in commit: https://github.com/cortezaproject/corteza-webapp-messaging/commit/b55f42321a92051761be505ce7a67775fa2c9904

**Closed as completed** 2019-08-28 10:20 UTC
Labels: Type: Bug
